author = "Filipe Carneiro"
baseURL = 'http://localhost:65145/hugo-bootstrap-theme/'
copyright = "Open-source <a class=\"text-muted text-decoration-none\" href=\"https://github.com/filipecarneiro/hugo-bootstrap-theme/blob/main/LICENSE\">MIT</a> Licensed."
title = "Brain Chip Memory Recorder"

timeZone = 'Europe/London'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = "hugo-bootstrap-theme"

disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

# Site Parameters
[params]
  description = "Never forget another important moment with Brain Chip Memory Technology"
  images = ['images/brainchip.png','images/site-feature-image.png']
  mainMenuLogo = "images/brainchip.png"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
author = "authors"
category = "categories"
series = 'series'
tag = "tags"

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
[module.hugoVersion]
extended = true
max = ""
min = "0.99.1"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "static"
target = "static"

[server]
[[server.headers]]
for = "/images/**"
[server.headers.values]
Access-Control-Allow-Origin = "*"
